sonar.projectKey=finance_tracker
sonar.projectName=Finance Tracker
sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/tests/**,**/.venv/**
sonar.tests=backend/tests,frontend/src/test
sonar.test.inclusions=backend/tests/**/*.py,frontend/src/test/**/*.js

# Test coverage paths
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
